env:
  global:
    - CONAN_DOCKER_32_IMAGES: 1
    - CONAN_CHANNEL: "stable"
    - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 CONAN_ARCHS=x86_64 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 CONAN_ARCHS=x86_64 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=5 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=6 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=7 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=8 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=9 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=10 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=11 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 CONAN_CURRENT_PAGE=12 CONAN_TOTAL_PAGES=12 CONAN_ARCHS=x86
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4 CONAN_ARCHS=x86_64
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4 CONAN_ARCHS=x86_64
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4 CONAN_ARCHS=x86_64
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4 CONAN_ARCHS=x86_64

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
